# Generated by Django 5.2.1 on 2025-05-24 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shotguns_owed', models.IntegerField(default=0)),
                ('shotguns_taken', models.IntegerField(default=0)),
            ],
        ),
    ]
